# Generated by Django 4.0.3 on 2022-03-04 18:06

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(\\+\\d{9,15})$', 'Phone number should include country code and should have a length between 9 and 15 characters')]),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
    ]
